//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace landlorder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int reviewID { get; set; }
        public int propertyID { get; set; }
        public string userID { get; set; }
        public int rating { get; set; }
        public string review1 { get; set; }
        public string apartmentnum { get; set; }
        public string landlordname { get; set; }
        public int repairrating { get; set; }
        public int communicationrating { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
