//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace landlorder.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Review
    {
        //ID's
        public int reviewID { get; set; }
        public int propertyID { get; set; }
        public string userID { get; set; }
        

        //Ratings
        [Required]
        [Display(Name = "Overall Rating")]
        public int rating { get; set; }

        [Required]
        [Display(Name = "Repair")]
        public int repairrating { get; set; }

        [Required]
        [Display(Name = "Communication")]
        public int communicationrating { get; set; }


        //Review & Misc info
        [Required]
        [Display(Name = "Review")]
        [DataType(DataType.MultilineText)]
        public string review1 { get; set; }

        [Display(Name = "Landlord Name")]
        public string landlordname { get; set; }

        [Display(Name = "Apartment Number(if applicable)")]
        public string apartmentnum { get; set; }

        
    
        public virtual Property Property { get; set; }
    }
}
